# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Test
      run: |
        npm install
        npm run build
        npm test
        
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: ESLint Action
        uses: hallee/eslint-action@1.0.1
